name = "NtToolBox"
uuid = "c4e28c0b-4b17-427e-8618-d509d166b272"
authors = ["Pierre Bréchet"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
